version: "2"
services: 
  mongo:
    hostname: mongodb
    container_name: mongodb
    image: mongo:4.4.3
    networks:
      - my-network
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]

  replica-setup:
    image: mongo:4.4.3
    networks:
      - my-network
    restart: on-failure
    ports:
      - "27018:27018"
    volumes:
      - ./scripts/setup-replica.sh:/scripts/setup-replica.sh
    entrypoint: ["bash" ,"/scripts/setup-replica.sh"]

networks:
  my-network:
    driver: bridge
